'use strict';
const defaults=[['2 яйця, гречка 150 г, огірок/помідор 200 г','Яблуко + мигдаль 20 г','Куряче філе 150 г, гречка 150 г, салат 200 г + 1 ч. л. олії','Банан','Запечена риба 150 г, овочі 250 г'],['Омлет із 2 яєць, цільнозерновий хліб 60 г, овочі 200 г','Груша + горіхи 20 г','Індичка 150 г, рис 150 г, салат 200 г','Яблуко','Куряче філе 150 г, тушковані овочі 300 г'],['2 яйця, авокадо 50 г, хліб 60 г, помідор','Банан + мигдаль 15 г','Яловичина 140 г, гречка 150 г, овочевий салат 200 г','Апельсин','Хек/минтай 180 г, броколі або овочева суміш 300 г'],['Гречка 180 г, 2 яйця, овочі 150–200 г','Яблуко + горіхи 20 г','Куряче філе 150 г, картопля запечена 200 г, салат 200 г','Ківі + банан невеликий','Індичка 150 г, овочі 300 г'],['Омлет: 2 яйця + овочі, хліб 60 г, авокадо 40 г','Груша + мигдаль 20 г','Риба 170 г, рис 150 г, салат 200 г','Яблуко','Курка 150 г, броколі/цвітна капуста 300 г'],['2 яйця, гречка 150 г, овочевий салат 200 г','Банан + горіхи 15 г','Індичка 150 г, гречка 150 г, овочі 200 г','Апельсин або яблуко','Запечена риба 170 г, овочі 300 г'],['Яєчня з 2 яєць, авокадо 50 г, хліб 60 г, овочі','Яблуко + мигдаль 20 г','Яловичина 150 г, рис 150 г, салат 200 г','Банан','Куряче філе 150 г, запечені овочі 300 г']];
const names=['Сніданок','Перекус','Обід','Перекус','Вечеря'], times=['07:00','10:30','13:30','16:30','19:00'], icons=['☀','◷','◉','◷','☾'];
const $=id=>document.getElementById(id), dateKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`, baseDate=s=>new Date(`${s}T12:00:00`), serial=s=>{let d=baseDate(s);return Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())/86400000;};
const fresh=()=>({version:1,start:dateKey(),plan:defaults.map(day=>day.map((text,i)=>({text,time:times[i]}))),done:{},notified:{},reminders:false,theme:'light'});
function valid(x){return x&&x.version===1&&typeof x.start==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(x.start)&&Number.isFinite(baseDate(x.start).getTime())&&dateKey(baseDate(x.start))===x.start&&Array.isArray(x.plan)&&x.plan.length===7&&x.plan.every(d=>Array.isArray(d)&&d.length===5&&d.every(m=>typeof m.text==='string'&&m.text.trim().length>0&&m.text.length<=2000&&/^([01]\d|2[0-3]):[0-5]\d$/.test(m.time)))&&['light','dark'].includes(x.theme)&&typeof x.reminders==='boolean'&&x.done&&typeof x.done==='object'&&!Array.isArray(x.done)&&Object.keys(x.done).every(k=>/^\d{4}-\d{2}-\d{2}-[0-4]$/.test(k)&&typeof x.done[k]==='boolean');}
let state=fresh(),storageOk=true;try{const raw=localStorage.getItem('ration-v1');if(raw){const parsed=JSON.parse(raw);if(valid(parsed))state=parsed;}}catch(e){storageOk=false;}
let today=dateKey(),selected=activeDay(),editIndex=0,editDay=selected,installPrompt=null,nextIndex=null,offlineReady=false;function activeDay(){const delta=serial(dateKey())-serial(state.start);return delta<0?0:delta%7;}function selectedDate(day=selected){let d=baseDate(today<state.start?state.start:today);d.setDate(d.getDate()+day-(today<state.start?0:activeDay()));return dateKey(d);}function escapeHTML(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}function toast(s){$('toast').textContent=s;$('toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.display='none',4500);}function save(){try{localStorage.setItem('ration-v1',JSON.stringify(state));storageOk=true;$('saveStatus').textContent='Збережено.';}catch(e){storageOk=false;$('saveStatus').textContent='Не вдалося зберегти. Створіть резервну копію.';toast('Сховище недоступне — зміни діють лише в цій сесії.');}}
const svgIcon=name=>`<svg class="icon" aria-hidden="true"><use href="#i-${name}"></use></svg>`;
function mealImage(text,i){const t=text.toLowerCase();if(i===1||i===3)return 'snack';if(i===0)return 'breakfast';if(/риб|хек|минтай/.test(t))return 'fish';if(/індич/.test(t))return 'turkey';if(/ялович|говя|теля/.test(t))return 'beef';return 'chicken';}
function render(){
 document.body.classList.toggle('dark',state.theme==='dark');$('theme').setAttribute('aria-label',state.theme==='dark'?'Увімкнути світлу тему':'Увімкнути темну тему');
 $('days').innerHTML=state.plan.map((_,i)=>{const d=baseDate(selectedDate(i)),weekday=d.toLocaleDateString('uk-UA',{weekday:'short'}),isToday=selectedDate(i)===today;return `<button data-day="${i}" class="${selected===i?'active ':''}${isToday?'isToday':''}" aria-pressed="${selected===i}" aria-label="День ${i+1}, ${d.toLocaleDateString('uk-UA')}${isToday?', сьогодні':''}"><span class="dayName">День ${i+1}</span><span class="dayNum">${String(d.getDate()).padStart(2,'0')}</span><span class="dayFlag">${isToday?'сьог.':weekday}</span></button>`;}).join('');
 const d=selectedDate();$('dateLabel').textContent=baseDate(d).toLocaleDateString('uk-UA',{weekday:'long',day:'numeric',month:'long',year:'numeric'});
 $('todayButton').textContent=today<state.start?'Початок циклу':'Сьогодні';
 $('meals').innerHTML=state.plan[selected].map((m,i)=>{const done=!!state.done[`${d}-${i}`];return `<article class="meal ${done?'done':''}" data-meal="${i}"><div class="timeColumn"><time>${m.time}</time><small>${i===0?'РАНОК':i===4?'ВЕЧІР':'ДЕНЬ'}</small></div><div class="mealCard"><img class="mealImage" src="images/${mealImage(m.text,i)}.webp" alt="Ілюстрація: ${names[i].toLowerCase()}" width="512" height="512" ${i>1?'loading="lazy"':''}><div class="mealInfo"><div class="mealTop"><h3>${names[i]}</h3><button class="editButton" data-edit="${i}" aria-label="Редагувати ${names[i]} о ${m.time}" title="Редагувати">${svgIcon('edit')}</button></div><p class="mealText">${escapeHTML(m.text)}</p><div class="mealBottom"><label class="checkLabel"><input type="checkbox" data-done="${i}" aria-label="${names[i]} о ${m.time}: виконано" ${done?'checked':''}><span class="checkBox">${svgIcon('check')}</span><span>${done?'Виконано':'Відмітити'}</span></label><span class="mealNumber">${String(i+1).padStart(2,'0')} / 05</span></div></div></div></article>`;}).join('');
 const n=state.plan[selected].filter((_,i)=>state.done[`${d}-${i}`]).length;
 $('count').textContent=`${n} / 5`;$('bar').style.width=n*20+'%';$('ring').style.setProperty('--progress',n*72+'deg');$('ring').setAttribute('aria-label',`Виконано ${n} з 5 прийомів їжі`);$('percent').innerHTML=`${n*20}<span>%</span>`;
 $('progressMessage').textContent=n===5?'Усі прийоми відмічено.':n===0?'Відмічайте прийоми в меню.':`Залишилося відмітити: ${5-n}.`;
 $('reminderLabel').textContent=state.reminders?'Увімкнено у відкритому застосунку':'Налаштуйте свій розклад';renderNext();connectionStatus();if(!storageOk)$('saveStatus').textContent='Сховище недоступне. Створіть резервну копію.';
}
function renderNext(){
 const now=new Date(),minutes=now.getHours()*60+now.getMinutes(),d=selectedDate();
 const pending=state.plan[selected].map((m,i)=>({...m,i,minutes:Number(m.time.slice(0,2))*60+Number(m.time.slice(3))})).filter(m=>!state.done[`${d}-${m.i}`]).sort((a,b)=>a.minutes-b.minutes);
 const upcoming=pending.filter(m=>d>today||(d===today&&m.minutes>=minutes));const m=upcoming[0]||pending[0];const overdue=!!m&&!upcoming.length;
 nextIndex=m?m.i:null;$('next').textContent=m?names[m.i]:'Усе відмічено';$('nextTime').textContent=m?m.time:'5 / 5';$('nextText').textContent=m?m.text:'Усі п’ять прийомів їжі за цей день відмічено.';
 const img='images/'+mealImage(m?m.text:state.plan[selected][4].text,m?m.i:4)+'.webp';if($('nextImage').getAttribute('src')!==img)$('nextImage').setAttribute('src',img);
 $('nextImage').alt=m?`Ілюстрація: ${names[m.i].toLowerCase()}`:'Ілюстрація страви';$('nextBadge').textContent=!m?'День завершено':overdue?'Ще не відмічено':d>today?'За розкладом':'Наступний прийом';$('photoIndex').textContent=m?`${String(m.i+1).padStart(2,'0')} / 05`:'05 / 05';
 let countdown='';if(!m)countdown='Ви виконали план дня';else if(d>today)countdown=baseDate(d).toLocaleDateString('uk-UA',{day:'numeric',month:'long'});else if(overdue)countdown='Можна відмітити в меню';else{const diff=m.minutes-minutes;countdown=diff===0?'Час прийому їжі':`Через ${diff>=60?Math.floor(diff/60)+' год ':''}${diff%60?diff%60+' хв':''}`.trim();}$('countdown').textContent=countdown;$('nextDone').hidden=!m;
 document.querySelectorAll('[data-meal]').forEach(row=>row.classList.toggle('upcoming',!!m&&Number(row.dataset.meal)===m.i&&!overdue));
}
function connectionStatus(){$('connectionLabel').textContent=offlineReady?(navigator.onLine===false?'Офлайн • меню доступне':'Меню доступне офлайн'):'Завантажено на пристрій';}
$('days').onclick=e=>{const b=e.target.closest('[data-day]');if(b){selected=Number(b.dataset.day);render();}};$('meals').onclick=e=>{const b=e.target.closest('[data-edit]');if(b){editIndex=Number(b.dataset.edit);editDay=selected;const m=state.plan[editDay][editIndex];$('editTitle').textContent=`День ${editDay+1} · ${names[editIndex]}`;$('editImage').src='images/'+mealImage(m.text,editIndex)+'.webp';$('editTime').value=m.time;$('editText').value=m.text;$('editor').showModal();}};$('meals').onchange=e=>{if(e.target.matches('[data-done]')){state.done[`${selectedDate()}-${e.target.dataset.done}`]=e.target.checked;save();render();}};$('editForm').onsubmit=e=>{e.preventDefault();const text=$('editText').value.trim();if(!text){$('editText').setCustomValidity('Вкажіть страви');$('editText').reportValidity();return;}state.plan[editDay][editIndex]={time:$('editTime').value,text};save();render();$('editor').close();toast('Раціон оновлено');};$('editText').oninput=()=> $('editText').setCustomValidity('');document.querySelectorAll('.close').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('theme').onclick=()=>{state.theme=state.theme==='light'?'dark':'light';save();render();};function openSettings(){$('start').value=state.start;notificationStatus();$('prefs').showModal();}$('settings').onclick=openSettings;$('reminderShortcut').onclick=openSettings;$('todayButton').onclick=()=>{selected=activeDay();render();};$('nextDone').onclick=()=>{if(nextIndex===null)return;state.done[`${selectedDate()}-${nextIndex}`]=true;save();render();toast('Прийом їжі відмічено');};window.addEventListener('online',connectionStatus);window.addEventListener('offline',connectionStatus);$('start').onchange=()=>{if(!$('start').value)return;state.start=$('start').value;selected=activeDay();save();render();};
function notificationStatus(){$('reminderLabel').textContent=state.reminders?'Увімкнено у відкритому застосунку':'Налаштуйте свій розклад';const supported='Notification'in window;$('notifyStatus').textContent=!supported?'Цей браузер не підтримує сповіщення. Скористайтеся календарем.':Notification.permission==='denied'?'Сповіщення заборонені в браузері. Змініть дозвіл у налаштуваннях сайту або скористайтеся календарем.':state.reminders&&Notification.permission==='granted'?'Увімкнено, поки застосунок відкритий.':'Сповіщення вимкнено.';$('notify').textContent=state.reminders?'Вимкнути сповіщення':'Увімкнути сповіщення';}
$('notify').onclick=async()=>{if(state.reminders){state.reminders=false;save();notificationStatus();return;}try{if(!('Notification'in window)||!('serviceWorker'in navigator))throw Error();const permission=await Notification.requestPermission();if(permission==='granted'){await Promise.race([navigator.serviceWorker.ready,new Promise((_,reject)=>setTimeout(()=>reject(Error('timeout')),5000))]);state.reminders=true;save();toast('Сповіщення увімкнено');}notificationStatus();}catch(e){toast('Сповіщення недоступні. Використайте календар.');}};
async function tick(){const d=dateKey();if(today!==d){today=d;selected=activeDay();render();}else renderNext();if(!state.reminders||!('Notification'in window)||Notification.permission!=='granted')return;const now=new Date(), t=now.getHours()*60+now.getMinutes();for(const [i,m]of state.plan[activeDay()].entries()){const [h,min]=m.time.split(':').map(Number),key=`${d}-${i}`;if(t>=h*60+min&&t<h*60+min+2&&!state.done[key]&&!state.notified?.[key]){try{const reg=await navigator.serviceWorker.ready;await reg.showNotification(`Час на ${names[i].toLowerCase()} · ${m.time}`,{body:m.text,icon:'icon-192.png',tag:key});state.notified=state.notified||{};state.notified[key]=true;save();toast(`${m.time} · ${names[i]}`);}catch(e){toast(`${m.time} · ${names[i]}: ${m.text}`);}}}}
function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('export').onclick=()=>download(JSON.stringify(state,null,2),`ration-${dateKey()}.json`,'application/json');$('import').onclick=()=>$('file').click();$('file').onchange=async()=>{try{const f=$('file').files[0];if(!f)return;if(f.size>500000)throw Error();const x=JSON.parse(await f.text());if(!valid(x))throw Error();if(!confirm('Замінити поточний раціон і відмітки даними з файлу?'))return;state={...x,notified:{},reminders:false};selected=activeDay();save();render();$('start').value=state.start;notificationStatus();toast('Копію відновлено');}catch(e){toast('Файл не містить коректної копії раціону.');}finally{$('file').value='';}};$('reset').onclick=()=>{if(confirm('Відновити початкові страви й час для всіх 7 днів?')){state.plan=fresh().plan;save();render();toast('Початковий раціон відновлено');}};
function icsEscape(s){return s.replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');}function fold(s){const enc=new TextEncoder();let out='',line='';for(const c of s){if(enc.encode(line+c).length>73){out+=line+'\r\n';line=' ';}line+=c;}return out+line;}
$('calendar').onclick=()=>{let lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//MyRation//UK','CALSCALE:GREGORIAN'];const stamp=new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d+Z$/,'Z');state.plan.forEach((day,j)=>day.forEach((m,i)=>{let d=baseDate(state.start);d.setDate(d.getDate()+j);const delta=serial(dateKey())-serial(dateKey(d));if(delta>0)d.setDate(d.getDate()+Math.ceil(delta/7)*7);const start=dateKey(d).replace(/-/g,'')+'T'+m.time.replace(':','')+'00';lines.push('BEGIN:VEVENT',`UID:ration-${state.start}-${j}-${i}@myration.local`,`DTSTAMP:${stamp}`,`DTSTART:${start}`,'DURATION:PT15M','RRULE:FREQ=WEEKLY',`SUMMARY:${icsEscape(`День ${j+1} · ${names[i]}`)}`,`DESCRIPTION:${icsEscape(m.text)}`,'BEGIN:VALARM','TRIGGER:PT0M','ACTION:DISPLAY',`DESCRIPTION:${icsEscape(names[i])}`,'END:VALARM','END:VEVENT');}));lines.push('END:VCALENDAR');download(lines.map(fold).join('\r\n')+'\r\n','ration-reminders.ics','text/calendar;charset=utf-8');toast('Імпортуйте файл у календар і перевірте сповіщення');};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;});$('install').onclick=async()=>{if(installPrompt){await installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;}else $('installHelp').showModal();};window.addEventListener('appinstalled',()=>{toast('Застосунок встановлено');installPrompt=null;});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').then(()=>navigator.serviceWorker.ready).then(()=>{offlineReady=true;connectionStatus();}).catch(()=>toast('Офлайн-режим недоступний у цьому браузері'));document.addEventListener('visibilitychange',()=>{if(!document.hidden)tick();});render();setInterval(tick,15000);tick();
